[System] Add SimpleAsyncResult.cs to the build.
Fixes a build break:
https://wrench.internalx.com/Wrench/WebServices/Download.aspx?workfile_id=2573365

	System.Net/WebConnectionStream.cs(636,12): error CS0246:
	The type or namespace name `SimpleAsyncResult' could not be found.
	Are you missing an assembly reference?