Fix build break.
https://wrench.internalx.com/Wrench/WebServices/Download.aspx?workfile_id=2583007

	System.Net/SimpleAsyncResult.cs(64,42): error CS0305:
	Using the generic type `System.Func<T1,T2,T3,TResult>' requires `4' type argument(s)

I have no idea WTF is going on here, but it builds if we use
Predicate<SimpleAsyncResult> instead of Func<SimpleAsyncResult, bool>.